/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author ahalh7876
 */
public class dataManagement extends javax.swing.JFrame {

    /**
     * Creates new form dataManagement
     */
    public dataManagement() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgPnl = new javax.swing.JPanel();
        titleLbl = new javax.swing.JLabel();
        primPromptLbl = new javax.swing.JLabel();
        name1PromptLbl = new javax.swing.JLabel();
        name1IPTF = new javax.swing.JTextField();
        mark1PromptLbl = new javax.swing.JLabel();
        mark1IPTF1 = new javax.swing.JTextField();
        mark1IPTF2 = new javax.swing.JTextField();
        mark1IPTF4 = new javax.swing.JTextField();
        mark1IPTF3 = new javax.swing.JTextField();
        avg1PromptLbl = new javax.swing.JLabel();
        avgOPTF = new javax.swing.JTextField();
        name1PromptLbl1 = new javax.swing.JLabel();
        name1IPTF1 = new javax.swing.JTextField();
        mark1PromptLbl1 = new javax.swing.JLabel();
        mark1IPTF8 = new javax.swing.JTextField();
        mark1IPTF7 = new javax.swing.JTextField();
        mark1IPTF6 = new javax.swing.JTextField();
        mark1IPTF5 = new javax.swing.JTextField();
        avg1PromptLbl1 = new javax.swing.JLabel();
        avgOPTF1 = new javax.swing.JTextField();
        mark1IPTF9 = new javax.swing.JTextField();
        mark1IPTF10 = new javax.swing.JTextField();
        mark1IPTF11 = new javax.swing.JTextField();
        name1IPTF2 = new javax.swing.JTextField();
        avgOPTF2 = new javax.swing.JTextField();
        mark1PromptLbl2 = new javax.swing.JLabel();
        avg1PromptLbl2 = new javax.swing.JLabel();
        name1PromptLbl2 = new javax.swing.JLabel();
        mark1IPTF12 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        titleLbl.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        titleLbl.setText("Ultimate Mark Management");

        primPromptLbl.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        primPromptLbl.setText("Please fill the text fields with the indicated information:");

        name1PromptLbl.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        name1PromptLbl.setText("Name:");

        name1IPTF.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N

        mark1PromptLbl.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        mark1PromptLbl.setText("Mark:");

        mark1IPTF1.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N

        mark1IPTF2.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N

        mark1IPTF4.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N

        mark1IPTF3.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N

        avg1PromptLbl.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        avg1PromptLbl.setText("Average:");

        avgOPTF.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N

        name1PromptLbl1.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        name1PromptLbl1.setText("Name:");

        name1IPTF1.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N

        mark1PromptLbl1.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        mark1PromptLbl1.setText("Mark:");

        mark1IPTF8.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N

        mark1IPTF7.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N

        mark1IPTF6.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N

        mark1IPTF5.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N

        avg1PromptLbl1.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        avg1PromptLbl1.setText("Average:");

        avgOPTF1.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N

        mark1IPTF9.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N

        mark1IPTF10.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N

        mark1IPTF11.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N

        name1IPTF2.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N

        avgOPTF2.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N

        mark1PromptLbl2.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        mark1PromptLbl2.setText("Mark:");

        avg1PromptLbl2.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        avg1PromptLbl2.setText("Average:");

        name1PromptLbl2.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        name1PromptLbl2.setText("Name:");

        mark1IPTF12.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N

        javax.swing.GroupLayout bgPnlLayout = new javax.swing.GroupLayout(bgPnl);
        bgPnl.setLayout(bgPnlLayout);
        bgPnlLayout.setHorizontalGroup(
            bgPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bgPnlLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(titleLbl)
                .addGap(111, 111, 111))
            .addGroup(bgPnlLayout.createSequentialGroup()
                .addGroup(bgPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bgPnlLayout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(primPromptLbl))
                    .addGroup(bgPnlLayout.createSequentialGroup()
                        .addGroup(bgPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(bgPnlLayout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(bgPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                                    .addComponent(name1PromptLbl)
                                    .addComponent(name1IPTF, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(bgPnlLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(bgPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                                    .addComponent(mark1PromptLbl)
                                    .addComponent(mark1IPTF1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(mark1IPTF2, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(mark1IPTF3, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(mark1IPTF4, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(bgPnlLayout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(bgPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                                    .addComponent(avg1PromptLbl)
                                    .addComponent(avgOPTF, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(48, 48, 48)
                        .addGroup(bgPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(name1PromptLbl1)
                            .addComponent(name1IPTF1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(mark1PromptLbl1)
                            .addComponent(mark1IPTF8, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(mark1IPTF7, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(mark1IPTF6, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(mark1IPTF5, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(avg1PromptLbl1)
                            .addComponent(avgOPTF1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(49, 49, 49)
                        .addGroup(bgPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(name1PromptLbl2, javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(name1IPTF2, javax.swing.GroupLayout.Alignment.CENTER, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(mark1PromptLbl2, javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(mark1IPTF10, javax.swing.GroupLayout.Alignment.CENTER, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(mark1IPTF12, javax.swing.GroupLayout.Alignment.CENTER, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(mark1IPTF11, javax.swing.GroupLayout.Alignment.CENTER, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(mark1IPTF9, javax.swing.GroupLayout.Alignment.CENTER, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(avg1PromptLbl2, javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(avgOPTF2, javax.swing.GroupLayout.Alignment.CENTER, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        bgPnlLayout.setVerticalGroup(
            bgPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgPnlLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titleLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(primPromptLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(bgPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(bgPnlLayout.createSequentialGroup()
                        .addComponent(name1PromptLbl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(name1IPTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(mark1PromptLbl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(mark1IPTF1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11)
                        .addComponent(mark1IPTF2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(mark1IPTF3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(mark1IPTF4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(avg1PromptLbl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(avgOPTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(bgPnlLayout.createSequentialGroup()
                        .addComponent(name1PromptLbl1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(name1IPTF1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(mark1PromptLbl1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(mark1IPTF8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11)
                        .addComponent(mark1IPTF7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(mark1IPTF6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(mark1IPTF5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(avg1PromptLbl1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(avgOPTF1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(bgPnlLayout.createSequentialGroup()
                        .addComponent(name1PromptLbl2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(name1IPTF2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(mark1PromptLbl2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(mark1IPTF10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11)
                        .addComponent(mark1IPTF12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(mark1IPTF11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(mark1IPTF9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(avg1PromptLbl2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(avgOPTF2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bgPnl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bgPnl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(dataManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(dataManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(dataManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(dataManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new dataManagement().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel avg1PromptLbl;
    private javax.swing.JLabel avg1PromptLbl1;
    private javax.swing.JLabel avg1PromptLbl2;
    private javax.swing.JTextField avgOPTF;
    private javax.swing.JTextField avgOPTF1;
    private javax.swing.JTextField avgOPTF2;
    private javax.swing.JPanel bgPnl;
    private javax.swing.JTextField mark1IPTF1;
    private javax.swing.JTextField mark1IPTF10;
    private javax.swing.JTextField mark1IPTF11;
    private javax.swing.JTextField mark1IPTF12;
    private javax.swing.JTextField mark1IPTF2;
    private javax.swing.JTextField mark1IPTF3;
    private javax.swing.JTextField mark1IPTF4;
    private javax.swing.JTextField mark1IPTF5;
    private javax.swing.JTextField mark1IPTF6;
    private javax.swing.JTextField mark1IPTF7;
    private javax.swing.JTextField mark1IPTF8;
    private javax.swing.JTextField mark1IPTF9;
    private javax.swing.JLabel mark1PromptLbl;
    private javax.swing.JLabel mark1PromptLbl1;
    private javax.swing.JLabel mark1PromptLbl2;
    private javax.swing.JTextField name1IPTF;
    private javax.swing.JTextField name1IPTF1;
    private javax.swing.JTextField name1IPTF2;
    private javax.swing.JLabel name1PromptLbl;
    private javax.swing.JLabel name1PromptLbl1;
    private javax.swing.JLabel name1PromptLbl2;
    private javax.swing.JLabel primPromptLbl;
    private javax.swing.JLabel titleLbl;
    // End of variables declaration//GEN-END:variables
}
